version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  customer_service:
    build:
      context: ./customer_service
    container_name: customer_service
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  invoice_service:
    build:
      context: ./invoice_service
    container_name: invoice_service
    ports:
      - "5001:5001"
    depends_on:
      - redis
